In [113]:
# 1 Write a function so that the columns of the output matrix are powers of the input
# vector.
# The order of the powers is determined by the increasing boolean argument. Specifically,
# when increasing is False, the i-th output column is the input vector raised element-wise
# to the power of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

In [114]:
import numpy as np  #package import

In [115]:
def matrixGeoProgession(x,n,increasingBoolean):
    l=[]
    if increasingBoolean==True: #condition for genratating the vander function in increasing or decreasing
        
        for item in x:
            v=[]
            for j in range(n):
                v.append(item**j)
            l.append(v)
        return np.array(l)
    
    else:
        for item in x:
            v=[]
            for j in range(n):
                v.append(item**j)
            l.append(v[::-1])
        return np.array(l)         
            
    

In [116]:
x=[1,2,3,6]

In [117]:
matrixGeoProgession(x,3,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [36,  6,  1]])

In [118]:
np.vander(x,3,False)   #Testing With the orignal Vander function using False Condtion

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [36,  6,  1]])

In [119]:
matrixGeoProgession(x,3,True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  6, 36]])

In [120]:
np.vander(x,3,True)   #Testing With the orignal Vander function using True Condtion

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  6, 36]])